### PR TITLE
Validate URLs when constructing Sarus object

### LINKED ISSUE #370: DOMException stacktrace gets lost when initializing Sarus with bogus URL
**Describe the bug**
When creating a new Sarus instance, providing an invalid URL hides the original stacktrace and fails in a hard to understand way.

**To Reproduce**
1. Create a blank Svelte/whatever starter project
2. In the main app page put:
```svelte
<script lang="ts">
    import Sarus from "@anephenix/sarus";
    new Sarus("bogus-url");
</script>
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

```
3. Load in browser (after running npm run dev or similar)
4. Inspect browser console
```
[vite] connecting... client.ts:18:8
[vite] connected. client.ts:150:14
[HMR][Svelte] Failed to rerender <+page> proxy.js:15:11
DOMException: An invalid or illegal string was specified proxy.js:19:13
[vite] hot updated: /src/routes/+page.svelte client.ts:479:12
```

**Expected behavior**
Calling new Sarus() should fail directly

**Desktop (please complete the following information):**
- Firefox-esr 102.15.0esr
- Sarus: 0.4.6

### PR DESCRIPTION
**Pull request by justuswilhelm**
This will better inform a user about invalid URLs when constructing a new Sarus object. It will already give an error during construction instead of the connect step. That way, we won't repeatedly try to connect to the same URL, despite it being invalid the whole time.

Add test case in __tests__ for

- Completely invalid URL (fails to be fed into new URL())
- Invalid protocol (must be ws / wss)

We use stock JS functionality for this, so no custom URL parser.

This should fix #370.

Please let me know if you have any preferences regarding testing, like splitting each new Sarus() case into a separate test case.

Note that this changed the type of `this.url`. If this is only ever used internally, it shouldn't cause any problems. On the other hand if a consumer of a Sarus object depends on the datatype of this.url, it might be better to keep it as `string`. Having it a proper URL type prevents us from doing anything silly with it. Let me know what you think about this particular change.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -46,6 +46,31 @@ const getMessagesFromStore = ({ storageType, storageKey }: StorageParams) => {
...
+    // TypeError, as specified by WHATWG URL Standard:
+    // https://url.spec.whatwg.org/#url-class (see constructor steps)
+    if (!(e instanceof TypeError)) {
+      throw e;
+    }
+    const { message } = e;
+    throw new Error(`The WebSocket URL is not valid: ${message}`);
+  }
+  const { protocol } = url;
+  if (protocol === "wss:" || protocol == "ws:") {
```
Comment (paulbjensen) [inline src/index.ts:66]: Spotted a `==` instead of a `===` here.

An alternative way to execute the logic could be an array includes call:

```javascript
['ws://', 'wss://'].includes(protocol)
```

File: __tests__/index/connectionOptions.test.ts [hunk 2]
```diff
@@ -18,6 +18,26 @@ describe("connection options", () => {
...
+    expect(() => {
+      new Sarus({ url: "invalid-url" });
+    }).toThrow("invalid");
+
+    expect(() => {
+      new Sarus({ url: "http://wrong-protocol" });
+    }).toThrow("have protocol");
+
+    expect(() => {
+      new Sarus({ url: "https://also-wrong-protocl" });
```
Comment (paulbjensen) [inline __tests__/index/connectionOptions.test.ts:34]: Misspelt 'protocol' here.

**Comment by paulbjensen** [comment]
Hi @justuswilhelm, spotted a few tweaks but otherwise the change is good 👍, and the URL type change is good as well.

**Comment by justuswilhelm** [comment]
Thanks so much for the review, I appreciate you taking the time. I have included the `includes` suggestion, and fixed the typo. The allowed protocols are in lib/constants.ts.

**Review by paulbjensen — APPROVED** [review]
